apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: go-hello-http
spec:
  generators:
  - list:
      elements:
      - cluster: in-cluster
        url: https://kubernetes.default.svc
  template:
    metadata:
      annotations:
        notifications.argoproj.io/subscribe.on-deployed.github: ""
      name: '{{cluster}}-go-hello-http'
    spec:
      project: default
      source:
        repoURL: https://github.com/etiennep/k8s-go-hello-http.git
        targetRevision: HEAD
        path: workloads
      destination:
        server: '{{url}}'
        namespace: default
      syncPolicy:
        automated: {}
