---
apiVersion: v1
kind: Service
metadata:
  name: go-hello-http
  labels:
    app.kubernetes.io/name: go-hello-http
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: go-hello-http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hello-http
  labels:
    app.kubernetes.io/name: go-hello-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: go-hello-http
  template:
    metadata:
      labels:
        app.kubernetes.io/name: go-hello-http
    spec:
      containers:
        - name: go-hello-http
          image: "etiennep/go-hello-http:sha-9e72885"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8090
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /hello
              port: http
          readinessProbe:
            httpGet:
              path: /hello
              port: http
          resources:
            {}
